### PR TITLE
Improve error messages

### PR DESCRIPTION
**Pull request by holtkamp**

### CODE REVIEW

**Comment by jderusse** [comment]
Thank you @holtkamp

**Comment by holtkamp** [comment]
Just wondering when scanning the code: why is an internal WebServer used, "just" to invoke `opcache_compile_file()`? Can that command not be invoked from CLI? Might be interesting to adopt a small section in the README.md about this.

**Comment by jderusse** [comment]
ahah, good question.

The purpose of the server is to isolate calls to `opcache_compile_file`. Because this function does not "just" compile the file, it also "evaluate" it and php does not allow to declare the same function/class/interface twice. (for instance, you'll get errors like `PHP Fatal error:  Cannot declare class Symfony\Flex\Lock, because the name is already in use in /srv/api/vendor/symfony/flex/src/Lock.php on line 19`)

And those classes are declared twice because of composer and the plugin, indeed, when running `composer warmup`, composer itself uses many classes from Symfony and other lib (console, finder, process, psr, ...) it the project you are warming up use one of this class, it won't be compiled.

**Comment by jderusse** [comment]
for the record, the first version of the project use a simple call to `php -l` to compile the file, but forking a process on each php file was much slower

**Comment by holtkamp** [comment]
>And those classes are declared twice because of composer and the plugin

Aah, ok, great response. I would say => ready to add to README.md 😄 

FYI: trying to get the plugin working as part of the [Heroku compile step](https://devcenter.heroku.com/articles/php-support#custom-compile-step) as we speak! Not sure it will work, since the "compile" step runs in a different directory structure as the eventual deployed application.

**Pull request merged**
